# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM wnameless/oracle-xe-11g

# Login http://localhost:8080/apex/apex_admin with following credential:
# username: ADMIN
# password: Oracle_11g

# hostname: localhost
# port: 49161
# sid: xe
# username: system
# password: oracle
# Password for SYS & SYSTEM

CMD ["/bin/sh"]
